#!/bin/bash

COLOR_CYAN='\033[1;36m'
COLOR_OFF='\033[0m'

containers=$(docker ps -aq | tail -r)

echo ""
for container in $containers
do
    name=$(docker inspect $container | jq '.[0] | .Name' | tr -d \"  | tr -d \/)
    ip=$(docker inspect $container | jq '.[0] | .NetworkSettings.IPAddress' | tr -d \"  | tr -d \/)
    echo -e "${name}: ${ip}"
done

echo ""
