#!/bin/bash

COLOR_CYAN='\033[1;36m'
COLOR_OFF='\033[0m'

containers=$(docker ps -aq | tail -r)

echo ""
echo -e "${COLOR_CYAN}Stoping containers${COLOR_OFF}"
docker stop $containers

echo ""
echo -e "${COLOR_CYAN}Removing loopback network aliases${COLOR_OFF}"

for container in $containers
do
    name=$(docker inspect $container | jq '.[0] | .Name' | tr -d \"  | tr -d \/)
    ip=$(docker inspect $container | jq '.[0] | .NetworkSettings.IPAddress' | tr -d \"  | tr -d \/)
    sudo ifconfig lo0 -alias $ip
    echo "${name}"
done

echo ""

